name: doc_connect_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  flutter_svg: ^2.0.5
  file_picker: ^5.2.11
  image_picker: ^0.8.7+4
  universal_io: ^2.2.0
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.2.5
  table_calendar: ^3.0.9
  firebase_core: ^2.10.0
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.5.3
  firebase_auth_web: ^5.2.2
  intl: ^0.18.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

