// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuRE6CSo4MlAYXuNtUaXFMC1cM1AcFMSc',
    appId: '1:781157587380:web:86829574ae84e0c398bae1',
    messagingSenderId: '781157587380',
    projectId: 'doc-connect-app',
    authDomain: 'doc-connect-app.firebaseapp.com',
    storageBucket: 'doc-connect-app.appspot.com',
    measurementId: 'G-4VN9L8RSYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP4KhC82AURjS0yoRRhQYANUzZso5JqPo',
    appId: '1:781157587380:android:1fee9ae486098a0698bae1',
    messagingSenderId: '781157587380',
    projectId: 'doc-connect-app',
    storageBucket: 'doc-connect-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk9r-Pn71h1Pmypx6t8CxGxqAyIl-OAP8',
    appId: '1:781157587380:ios:a32eb03512c9f4b698bae1',
    messagingSenderId: '781157587380',
    projectId: 'doc-connect-app',
    storageBucket: 'doc-connect-app.appspot.com',
    iosClientId: '781157587380-sv5rge3vdj90o2s880r6673u8m9aepgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.docConnectApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk9r-Pn71h1Pmypx6t8CxGxqAyIl-OAP8',
    appId: '1:781157587380:ios:a32eb03512c9f4b698bae1',
    messagingSenderId: '781157587380',
    projectId: 'doc-connect-app',
    storageBucket: 'doc-connect-app.appspot.com',
    iosClientId: '781157587380-sv5rge3vdj90o2s880r6673u8m9aepgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.docConnectApp',
  );
}
